---
title: Mapping of spaCy string values to `tabulaedspy` objects
---


## Analytic type

`tabulaedspy` defines 11 analytic types. Use this table to determine the correct analytic type to apply for a given spaCy `token`.

| spAcy token tags | analytic type in `tabulaedspy` |
| --- | --- |
| `token.pos_` is `NOUN` | `noun` |
| `token.pos_` is `PRON` | `pronoun` |
| `token.pos_` is  `ADJ` | `adjective` |
| `token.pos_` is  `ADV` | `adverb` |
|`token.morph` includes  `VerbForm=Fin` | `finite verb` |
| `token.morph` includes `VerbForm=Inf` | `infinitive` |
| `token.morph` includes  `VerbForm=Part` | `participle` |
|  `token.morph` includes  `VerbForm=Sup` | `supine` |
|  `token.morph` includes   `VerbForm=Ger` | `gerund` |
|  `token.morph` includes  `VerbForm=Gdv` | `gerundive` |
| `token.morph`  is empty | `uninflected` |



## Properties by type

Use this table to determine the morphological properties required for each analytic type:

| Analytic type | Properties |
| ---  | --- | 
|  `noun` | `gender`, `case`, `number` |
|   `pronoun` | `gender`, `case`, `number` |
| `adjective` | `gender`, `case`, `number`, `degree ` |
| `adverb` | `degree` |
|    `finite verb` | `tense`, `mood`, `voice`, `person`, `number ` |
| `infinitive` | `tense`, `voice ` |
| `participle` | `tense`, `voice`, `gender`, `case`, `number ` |
|  `supine` | `case` |
|    `gerund` | `case` |
| `gerundive` | `gender`, `case`, `number ` |
|  `uninflected` | `uninflected_type` |



## Values for morphological properties

Use these tables to determine the value for each morphological property required for each analytic type:



### Gender

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Gender=Masc` | `masculine` |
| `Gender=Fem` | `feminine` |
| `Gender=Neut` | `neuter` |

### Case

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Case=Nom`| `nominative` |
| `Case=Gen` | `genitive` |
| `Case=Dat` | `dative` |
| `Case=Acc` | `accusative` |
| `Case=Abl` | `ablative` |
| `Case=Voc` | `vocative` |



### Number

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Number=Sing` | `singular` |
| `Number=Plur` | `plural` |




### Degree

latincy does not appear to tag degree of adjectives and adverbs.

`tabulaedspy` requires one of these values for `Degree`: `positive`, `comparative`, `superlative`

### Tense

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Tense=Pres` | `present` |
|`Aspect=Imp` and  `Tense=Past` |  `imperfect` |
| `Aspect=Imp` and `Tense=Fut`|  `future` |
|`Aspect=Perf` and  `Tense=Past`|  `perfect` |
|`Tense=Pqp` | `pluperfect` |
|`Aspect=Perf` and `Tense=Fut`| `future_perfect` |

### Mood




| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Mood=Ind` | `indicative` |
| `Mood=Sub` | `subjunctive` |
| `Mood=Imp` | `imperative` |




### Voice

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Voice=Act` | `active` |
| `Voice=Pass` | `passive` |



### Person

| spaCy `token.morph` includes |  value |
| --- | --- | 
| `Person=1` | `first` |
| `Person=2` | `second` |
| `Person=3` | `third` |



### Uninflected type

spaCy `token.morph` is empty.

| spaCy `token.pos_` is |  value |
| --- | --- | 
| `CCONJ` | `conjunction` |
| `ADP` | `preposition` |
| `ADV`| `adverb` |
| `NUM` | `number` |
| `INTJ` | `interjection` |
| `PART` | `particle` |
| `X` but see following | `foreign` |

spaCy `token.pos_` value  `X` generically marks unintelligible tokens so encompasses `foreign` but also could include errors.